export { default as Courses } from './Courses';
export { default as Grades } from './Grades';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as News } from './News';
export { default as Panel } from './Panel';
export { default as Profile } from './Profile';
export { default as Training } from './Training';
export { default as CodeBot } from './CodeBot';